/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    /** Health check */
    get: {
      responses: {
        /** @description Service status and config */
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
      };
    };
  };
  "/search": {
    /** Search top documents */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SearchRequest"];
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": components["schemas"]["SearchResponse"];
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/answer": {
    /** Answer with sources */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["AnswerRequest"];
        };
      };
      responses: {
        /** @description Answer payload */
        200: {
          content: {
            "application/json": components["schemas"]["AnswerResponse"];
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": components["schemas"]["ErrorResponse"];
          };
        };
      };
    };
  };
  "/history": {
    /** Recent queries and answers */
    get: {
      parameters: {
        query?: {
          limit?: number;
        };
      };
      responses: {
        /** @description History items */
        200: {
          content: {
            "application/json": components["schemas"]["HistoryResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SearchRequest: {
      /** @example How to list iblock elements via CIBlockElement::GetList? */
      query: string;
    };
    AnswerRequest: {
      /** @example How to create a user? */
      query: string;
      /**
       * @example auto
       * @enum {string}
       */
      mode?: "auto" | "llm" | "extractive";
    };
    SearchResult: {
      /** @example docs/iblock/classes/ciblockelement/getlist.md */
      path?: string;
      /** @example CIBlockElement::GetList */
      title?: string;
      /** @example Examples > Basic usage */
      heading_path?: string;
      /** @example D7 */
      section?: string;
      /** @example iblock */
      module?: string;
    };
    SearchResponse: {
      query?: string;
      results?: components["schemas"]["SearchResult"][];
    };
    AnswerResponse: {
      answer?: string;
      sources?: string[];
      /** @enum {string} */
      mode?: "llm" | "extractive" | "fallback";
      timings_ms?: {
        [key: string]: number;
      };
    };
    HealthResponse: {
      /** @example ok */
      status?: string;
      /** @example /mnt/c/informika/docs/bitrix-docs-new/docs */
      vault_root?: string;
      /** @example /mnt/c/informika/docs/bitrix-docs-new/.rag */
      rag_data_dir?: string;
      indexes_present?: {
        chunks?: boolean;
        bm25?: boolean;
      };
      database?: {
        ok?: boolean;
        /** @example postgresql */
        dialect?: string;
        pgvector?: boolean | null;
        error?: string | null;
      };
      /** @enum {string} */
      vector_backend?: "qdrant" | "pgvector" | "none";
      /** @example http://localhost:6333 */
      qdrant_url?: string;
      /** @example bitrix_docs */
      qdrant_collection?: string;
      bge_base_url_set?: boolean;
      /** @example gpt-5.2 */
      openai_model?: string;
    };
    ErrorResponse: {
      detail?: string;
    };
    HistoryItem: {
      /** @example 123 */
      id?: number;
      query?: string;
      mode?: string | null;
      /** Format: float */
      latency_ms?: number | null;
      /** Format: date-time */
      created_at?: string;
      answer?: string | null;
      sources?: string[];
    };
    HistoryResponse: {
      items?: components["schemas"]["HistoryItem"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
